available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT - это известная модель. Она <b>быстрая</b> и <b>дешевая</b>. Идеально подходит для повседневных задач. Если есть задачи, с которыми она не справляется, попробуйте <b>GPT-4</b>.
    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Умная: 3
      Быстрая: 5
      Дешевая: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: ChatGPT - это известная модель. Она <b>быстрая</b> и <b>дешевая</b>. Идеально подходит для повседневных задач. Если есть задачи, с которыми она не справляется, попробуйте <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Умная: 3
      Быстрая: 5
      Дешевая: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 - это <b>самая умная</b> и самая продвинутая модель в мире. Но она медленнее и не так экономична, как ChatGPT. Лучший выбор для <b>сложных</b> интеллектуальных задач.
    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Умная: 5
      Быстрая: 2
      Дешевая: 2

  text-davinci-003:
    type: completion
    name: davinci
    description: text-davinci-003 - это устаревшая модель. На самом деле <b>нет причин использовать ее</b>, потому что она дороже и медленнее, чем ChatGPT, и намного глупее чем ChatGPT.
    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Умная: 3
      Быстрая: 2
      Дешевая: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006